**Matrix Multiplication**

In [1]:
import numpy as np

In [2]:
def matrixMultiplication(maxtrixA, matrixB):
    RA, CA = matrixA.shape
    RB, CB = matrixB.shape

    if CA != RB:
        print("Matrix Multiplication Not Possible")
        return 0
        
    X, Y = RA, CB
    n = CA

    result = np.zeros((X, Y))
    for i in range(X):
        for j in range(Y):
            for k in range(n):
                result[i][j] += matrixA[i][k]*matrixB[k][j]
            
    print(f"A =\n{matrixA}\n\nB\n{matrixB}\n\nA x B =\n{result}")

In [3]:
matrixA = np.random.randint(10, 19, size=(2, 3))
matrixB = np.random.randint(1, 9, size=(3, 4))

In [4]:
matrixMultiplication(matrixA, matrixB)

A =
[[13 15 10]
 [12 10 14]]

B
[[5 7 2 6]
 [7 2 5 5]
 [3 5 5 2]]

A x B =
[[200. 171. 151. 173.]
 [172. 174. 144. 150.]]
