## Make a 2-D matrix

- Write a program which takes 2 digits - m, n as input and generates a 2-dimensional numpy matrix of order m, n
- The element value in the i-th row and j-th column of the array should be i*j.
- Note: i=0,1..,X-1; j=0,1,...,Y-1.
- Example Suppose the following inputs are given to the program: 3,5 Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [1]:
import numpy as np

In [2]:
def makeMatrix(rows: int = 1, cols: int = 1):

    if rows <= 0 or cols <= 0:
        raise ValueError("Rows and columns must be non-negative integers.")

    array = np.fromfunction(lambda i, j: i * j, (rows, cols), dtype=int)
    return array

In [3]:
print(makeMatrix(3, 5))

[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [4]:
print(makeMatrix(3.8, 5.5))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
print(makeMatrix(-4, 5))

ValueError: Rows and columns must be non-negative integers.

In [6]:
print(makeMatrix(cols=4))

[[0 0 0 0]]


In [7]:
print(makeMatrix())

[[0]]
